In [2]:
import sentencepiece as sp

In [3]:
model = sp.SentencePieceProcessor(model_file='data/multi30k/m_en_de.model')

In [5]:
tokens = model.encode('hello, how is your day?')
tokens

[1092, 14908, 14930, 4204, 65, 14826, 1119, 14985]

In [6]:
''.join([model.id_to_piece(token) for token in tokens])

'▁hello,▁how▁is▁your▁day?'

In [12]:
model.unk_id(), model.bos_id(), model.eos_id(), model.pad_id()

(0, 1, 2, 3)

In [34]:
model.piece_to_id(' a'), model.unk_id()

(0, 0)

In [37]:
model.encode('a', out_type=str), model.encode('a', out_type=int)

(['▁a'], [5])

In [48]:
import numpy as np
import torch as torch

In [49]:
x = torch.randn(2, 3)
x

tensor([[-0.0785,  0.2897, -0.3207],
        [ 0.7577,  1.2845,  0.2301]])

In [60]:
v, i = torch.topk(x.flatten(), 3)
v, i

(tensor([1.2845, 0.7577, 0.2897]), tensor([4, 3, 1]))

In [47]:
np.array(np.unravel_index(i, x.shape)).T

array([[1, 2],
       [1, 0],
       [0, 2]])

In [62]:
torch.all(torch.zeros((3, 3)))

tensor(False)